//Bài 1: Tính tiền lương nhân viên

var SalaryOneDay = 250000;
var Day = 30;
var Salary = 0;
var Salary = SalaryOneDay * Day;
console.log("Salary = ", Salary);

//Bài 2: Tính giá trị trung bình

var One = 3.4;
var Two = 4.5;
var Three = 5.1;
var Four = 5.7;
var Five = 9.2;
var arithmeticMedium = 0;
var arithmeticMedium = (One + Two + Three + Four + Five) / 5;
console.log("arithmeticMedium = ",arithmeticMedium);

//Bài 3: Tính USD

var VND = 23.500;
var USD = 4;
var currency = 0;
var currency = VND * USD;
console.log("Currency Exchange", currency);

//Bài 4: Tính chu vi, diện tích hình chữ nhật

var long = 5;
var wide = 6;
var S = 0;
var P = 0;
var S = long * wide;
var P = (long + wide) * 2;
console.log("area = ", S);
console.log("perimeter =", P);

//Bài 5: Tính tổng 2 ký số

var number = 44;

var numberOne = number % 10;
var numberTwo = Math.floor(number / 10);

var sum = 0;

var sum = numberOne + numberTwo;

console.log("Sum two number = ",sum);


